before_script:
  - CHCP 65001

variables:
  BRANCH_FEATURE: feature
  BRANCH_PREPROD: preprod
  BRANCH_DEV: dev
  BRANCH_PROD: main
  APP_IMAGE: $APP_IMAGE_NAME
  JACOCO_BUILD_FILES_PATH: build/

stages:
  - test
  - build
  - deploy
  - release

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "feature" || $CI_COMMIT_BRANCH == "dev" 
          || $CI_COMMIT_BRANCH == "preprod" || $CI_COMMIT_BRANCH == "main"

test-job:
  stage: test
  script:
    - ./gradlew clean test
  cache:
    paths:
      - $JACOCO_BUILD_FILES_PATH
    policy: push
  tags:
    - windows


code-quality:
  stage: test
  cache:
    paths:
      - $JACOCO_BUILD_FILES_PATH
    policy: pull
  script:
    - ./gradlew sonar
  tags:
    - windows


build-job:
  stage: build
  before_script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
  script:
    - ./gradlew clean bootJar
    - docker build -t ${APP_IMAGE}:$(git describe --tags --abbrev=0)-${CI_COMMIT_BRANCH} .
    - docker push ${APP_IMAGE}:$(git describe --tags --abbrev=0)-${CI_COMMIT_BRANCH}
  tags:
    - windows


.deploy-to-stand-template:
  stage: deploy
  variables:
    DEPLOY_COMMAND: helm upgrade --install
                    --set backendUserService.image.version=$(git describe --tags --abbrev=0)-${CI_COMMIT_BRANCH}
                    backend-user-service-${ENV} ./backend-user-service
                    -f ./backend-user-service/values-${ENV}.yml
  script:
    - cd ./chart
    - Invoke-Expression $DEPLOY_COMMAND
  environment:
    name: $ENV
  tags:
    - windows


deploy-to-feature:
  extends: .deploy-to-stand-template
  variables:
    ENV: feature
  rules:
    - if: $CI_COMMIT_BRANCH == $BRANCH_FEATURE


deploy-to-dev:
  extends: .deploy-to-stand-template
  variables:
    ENV: dev
  rules:
    - if: $CI_COMMIT_BRANCH == $BRANCH_DEV


deploy-to-preprod:
  extends: .deploy-to-stand-template
  variables:
    ENV: preprod
  rules:
    - if: $CI_COMMIT_BRANCH == $BRANCH_PREPROD
      when: manual


deploy-to-prod:
  extends: .deploy-to-stand-template
  variables:
    ENV: prod
  rules:
    - if: $CI_COMMIT_BRANCH == $BRANCH_PROD
      when: manual


release-job:
  stage: release
  rules:
  #  - if: $CI_COMMIT_TAG
  #    when: never
    - if: $CI_COMMIT_REF_NAME == $BRANCH_PREPROD #$CI_COMMIT_BRANCH == $BRANCH_PROD
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Latest stable version."
  script:
    - echo "Creating release"
  only:
    - tags
  tags:
    - windows