version: '3'
services:
  psql:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgre_user
      - POSTGRES_PASSWORD=postgre_secret_password
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
