apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendUserService.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backendUserService.label.app }}
spec:
  replicas: {{ .Values.backendUserService.replicas.count}}
  selector: 
    matchLabels:
      app: {{ .Values.backendUserService.label.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendUserService.label.app }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
      - name: {{ .Values.backendUserService.container.name }}
        image: {{ .Values.backendUserService.image.name }}:{{ .Values.backendUserService.image.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.backendUserService.container.port }}
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: DATABASE_URL
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: DATABASE_PASSWORD
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: MINIO_ENDPOINT
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: MINIO_SECRET_KEY
        - name: MINIO_REGION
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: MINIO_REGION
        - name: MINIO_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: MINIO_BUCKET_NAME
        - name: ZIPKIN_TRACING_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: ZIPKIN_TRACING_ENDPOINT
        - name: KEYCLOAK_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: KEYCLOAK_ISSUER_URI
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: KEYCLOAK_CLIENT_SECRET

        - name: AUTH_SERVICE_API_ROOT_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: AUTH_SERVICE_API_ROOT_URL
        - name: AUTH_SERVICE_API_ADMIN_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: AUTH_SERVICE_API_ADMIN_CLIENT_ID
        - name: AUTH_SERVICE_API_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: AUTH_SERVICE_API_USERNAME
        - name: AUTH_SERVICE_API_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configMap.name }}
              key: AUTH_SERVICE_API_PASSWORD
      imagePullSecrets:
        - name: private-docker-registry


---


apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendUserService.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector: 
    app: {{ .Values.backendUserService.label.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.backendUserService.service.port }}
    targetPort: {{ .Values.backendUserService.container.port }}
    nodePort: {{ .Values.backendUserService.service.nodePort }}


---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: {{ .Values.namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.namespace }}-user-service-ingress-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /user-service
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backendUserService.service.name }}
            port:
              number: {{ .Values.backendUserService.service.port }}