server:
  port: 8080
  servlet:
    context-path: /user-service

springdoc:
  swagger-ui:
    path: /api/docs

spring:
  application:
    name: user-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/users}
    username: ${DATABASE_USER:postgre_user}
    password: ${DATABASE_PASSWORD:postgre_secret_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9080/realms/social-network}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9080/realms/social-network}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:user-service}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:AlJBczq2LsIY1Dg0yICMdrnys9J3sudJ}
            scope: openid

aws:
  s3:
    minio:
      endpoint: ${MINIO_ENDPOINT:http://localhost:9100/}
      signer: AWSS3V4SignerType
      access-key: ${MINIO_ACCESS_KEY:C6tyGJ8XsmMLQd2noc34}
      secret-key: ${MINIO_SECRET_KEY:yCZmp8CAKTID4uXCLxNdfpTlIVEw5zqa4WftwRfu}
      region: ${MINIO_REGION:ru-center}
      bucket-users: ${MINIO_BUCKET_NAME:users}


management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0


logging:
  pattern:
    correlation: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


auth-service:
  api:
    admin-client-id: ${AUTH_SERVICE_API_ADMIN_CLIENT_ID:admin-cli}
    root-url: ${AUTH_SERVICE_API_ROOT_URL:http://localhost:9080}
    username: ${AUTH_SERVICE_API_USERNAME:admin}
    password: ${AUTH_SERVICE_API_PASSWORD:admin}
    realm-name: ${AUTH_SERVICE_API_REALM_NAME:social-network}