server:
  port: 8080
  ssl:
    enabled: true
    key-store: ${KEY_STORE_FILE_PATH:classpath:keystore/keystore.p12}
    key-store-password: ${KEY_STORE_PASSWORD:useruser}
    key-store-type: PKCS12
    key-alias: ${KEY_STORE_ALIAS:localhost}


spring:
  application:
    name: user-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/users?ssl=true&sslmode=require}
    username: ${DATABASE_USER:postgre_user}
    password: ${DATABASE_PASSWORD:postgre_secret_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
      format_sql: true
    show-sql: false


aws:
  s3:
    minio:
      endpoint: ${MINIO_ENDPOINT:https://localhost:9100/}
      signer: AWSS3V4SignerType
      access-key: ${MINIO_ACCESS_KEY:xT1n9rCm9ZPrbdomoNEq}
      secret-key: ${MINIO_SECRET_KEY:B5QO9kmd4vFkrp5O1dfJd3KXaO0HMpRnCGRoGNFk}
      region: ${MINIO_REGION:ru-center}
      bucket-posts: ${MINIO_BUCKET_NAME:users}


management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0


logging:
  pattern:
    correlation: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"