server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore/keystore.p12
    key-store-password: useruser
    key-store-type: PKCS12
    key-alias: localhost


spring:
  application:
    name: user-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/users}
    username: ${DATABASE_USER:postgre_user}
    password: ${DATABASE_PASSWORD:postgre_secret_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
      format_sql: true
    show-sql: false


aws:
  s3:
    minio:
      endpoint: ${MINIO_ENDPOINT:http://localhost:9100/}
      signer: AWSS3V4SignerType
      access-key: ${MINIO_ACCESS_KEY:QEb84E8lIP5QXuNLrLWq}
      secret-key: ${MINIO_SECRET_KEY:sE5eBmARSGAPrNC52gVzyiizKUgDfGCex0BBD3NG}
      region: ${MINIO_REGION:ru-center}
      bucket-posts: ${MINIO_BUCKET_NAME:users}


management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0


logging:
  pattern:
    correlation: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"