namespace: &namespace test

database:
  storagePath: /postgresql-storage-test
  service:
    nodePort: 30003


backendUserService:
  image:
    version: latest-test
  service:
    nodePort: 30002


ingress:
  host: userservice-test.local