namespace: &namespace default


configMap:
  name: user-service-config


database:
  name: users
  username: postgre_user
  password: postgre_secret_password
  storagePath: /user-service/postgresql-storage-default
  deployment:
    name: deployment-postgresql
    namespace: *namespace
  replicas:
    count: 1
  label:
    app: postgresql
  container:
    name: postgresql-container
    port: 5432
  image:
    name: postgres
    version: latest
  service:
    name: service-postgresql
    port: 5432
    nodePort: 30001


backendUserService:
  label:
    app: backend-user-service
  deployment:
    name: deployment-backend-user-service
    namespace: *namespace
  replicas:
    count: 1
  container:
    name: backend-user-service-container
    port: 8080
  image:
    name: euchekavelo/backend-user-service
    version: latest-default
  service:
    name: service-backend-user-service
    port: 80
    nodePort: 30000
  datasource:
    prefixConnectionUrl: jdbc:postgresql


s3:
  label:
    app: minio
  service:
    name: minio-service
    ui:
      port: 9001
      nodePort: 30002
    server:
      port: 9000
      nodePort: 30003
  ingress:
    name: minio-ingress
    host: user-service-minio-default.local
  statefulSet:
    name: minio-statefulset
    container:
      name: minio-container
      ui:
        port: 9001
      server:
        port: 9000
    image:
      name: quay.io/minio/minio
      version: latest
  volume:
    name: minio-pvc
    storagePath: /user-service/minio-storage-default
  minioRegion: ru-center
  minioBucketName: users


zipkin:
  label:
    app: zipkin-user-service
  deployment:
    name: deployment-zipkin-user-service
    namespace: *namespace
  replicas:
    count: 1
  container:
    name: zipkin-user-service-container
    port: 9411
  image:
    name: openzipkin/zipkin
  service:
    name: service-zipkin-user-service
    port: 9411
    nodePort: 30004


ingress:
  name: backend-user-service-ingress
  host: user-service-default.local