namespace: &namespace preprod

database:
  storagePath: /user-service/postgresql-storage-preprod
  service:
    nodePort: 30130


backendUserService:
  image:
    version: latest-preprod
  service:
    nodePort: 30131


s3:
  service:
    ui:
      nodePort: 30132
    server:
      nodePort: 30133
  ingress:
    host: user-service-minio-preprod.local
  volume:
    storagePath: /user-service/minio-storage-preprod


zipkin:
  service:
    nodePort: 30134


ingress:
  host: user-service-preprod.local