namespace: &namespace feature

database:
  storagePath: /postgresql-storage-feature
  service:
    nodePort: 30013


backendUserService:
  image:
    version: latest-feature
  service:
    nodePort: 30012


ingress:
  host: userservice-feature.local