namespace: &namespace prod

database:
  storagePath: /user-service/postgresql-storage-prod
  service:
    nodePort: 30140


backendUserService:
  image:
    version: latest-prod
  service:
    nodePort: 30141


s3:
  service:
    ui:
      nodePort: 30142
    server:
      nodePort: 30143
  ingress:
    host: user-service-minio-prod.local
  volume:
    storagePath: /user-service/minio-storage-prod


zipkin:
  service:
    nodePort: 30144


ingress:
  host: user-service-prod.local