namespace: &namespace test

database:
  storagePath: /user-service/postgresql-storage-test
  service:
    nodePort: 30150


backendUserService:
  image:
    version: latest-test
  service:
    nodePort: 30151


s3:
  service:
    ui:
      nodePort: 30152
    server:
      nodePort: 30153
  ingress:
    host: user-service-minio-test.local
  volume:
    storagePath: /user-service/minio-storage-test


zipkin:
  service:
    nodePort: 30154


ingress:
  host: user-service-test.local