version: '3'
services:
  sonarqube:
    image: sonarqube:9.9.4-community
    container_name: sonarqube
    ports:
      - "9000:9000"


  psql:
    image: postgres:latest
    container_name: psql
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgre_user
      - POSTGRES_PASSWORD=postgre_secret_password
    volumes:
      - database_data:/var/lib/postgresql/data/


  minio:
    image: bitnami/minio:2024.12.18
    container_name: minio
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_storage:/data
    command: minio server /data --console-address :9001
    user: "${UID}:${GID}"


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"


  keycloak:
    image: bitnami/keycloak:26.0.1
    container_name: keycloak
    depends_on:
      - psql
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: psql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: postgre_user
      KEYCLOAK_DATABASE_PASSWORD: postgre_secret_password
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_NAME: users
    ports:
      - "9080:8080"


volumes:
  database_data:
  minio_storage: