version: '3'
services:
  sonarqube:
    image: sonarqube:9.9.4-community
    container_name: sonarqube
    ports:
      - "9000:9000"


  psql:
    image: postgres:latest
    container_name: psql
    ports:
      - "5432:5432"
    restart: on-failure
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/postgresql_service.crt
      -c ssl_key_file=/var/lib/postgresql/postgresql_service.key
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgre_user
      - POSTGRES_PASSWORD=postgre_secret_password
    volumes:
      - database_data:/var/lib/postgresql/data/
      - ./postgresql/init:/docker-entrypoint-initdb.d
      - $HOME/Desktop/test/postgresql_service.crt:/var/lib/postgresql/postgresql_service.crt
      - $HOME/Desktop/test/postgresql_service.key:/var/lib/postgresql/postgresql_service.key
    user: "${UID}:${GID}"


  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SCHEME: https
    volumes:
      - minio_storage:/data
      - $HOME/Desktop/test/root_ca.crt:/certs/CAs/root_ca.crt
      - $HOME/Desktop/test/minio_service.crt:/certs/public.crt
      - $HOME/Desktop/test/minio_service.key:/certs/private.key


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"


  keycloak:
    image: bitnami/keycloak:26.0.1
    container_name: keycloak
    depends_on:
      - psql
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: psql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: postgre_user
      KEYCLOAK_DATABASE_PASSWORD: postgre_secret_password
      KEYCLOAK_DATABASE_SCHEMA: users_scheme
      KEYCLOAK_DATABASE_NAME: users
    ports:
      - "9080:8080"


volumes:
  database_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/Desktop/Development/test
  minio_storage:
  keycloak_storage: