namespace: &namespace default


configMap:
  name: user-service-config


database:
  name: users_db
  username: postgre_user
  password: postgre_secret_password
  storagePath: /var/lib/postgresql/data
  statefulset:
    name: postgresql-statefulset
    namespace: *namespace
  replicas:
    count: 1
  label:
    app: postgresql
  container:
    name: postgresql-container
    port: 5432
  image:
    name: postgres
    version: latest
  service:
    name: postgresql-service
    port: 5432
    nodePort: 30001


backendUserService:
  label:
    app: backend-user-service
  deployment:
    name: deployment-backend-user-service
    namespace: *namespace
  replicas:
    count: 1
  container:
    name: backend-user-service-container
    port: 8080
  image:
    name: euchekavelo/backend-user-service
    version: latest-default
  service:
    name: service-backend-user-service
    port: 8080
    nodePort: 30000
  datasource:
    prefixConnectionUrl: jdbc:postgresql


s3:
  label:
    app: minio
  service:
    name: minio-service
    ui:
      port: 9001
      nodePort: 30002
    server:
      port: 9000
      nodePort: 30003
  statefulSet:
    name: minio-statefulset
    container:
      name: minio-container
      ui:
        port: 9001
      server:
        port: 9000
    image:
      name: quay.io/minio/minio
      version: latest
  volume:
    name: minio-pvc
    storagePath: /var/lib/minio
  minioRegion: ru-center
  minioBucketName: users


zipkin:
  label:
    app: zipkin
  deployment:
    name: zipkin-deployment
    namespace: *namespace
  replicas:
    count: 1
  container:
    name: zipkin-container
    port: 9411
  image:
    name: openzipkin/zipkin
  service:
    name: zipkin-service
    port: 9411
    nodePort: 30004


keycloak:
  issuerUri : https://euchekavelo.tw1.ru/auth-service/realms/social-network
  clientId : user-service
  clientSecret : msi1xut8HHefU5xR1DIYyH48OUIluCmd

authService:
  api:
    rootUrl : https://euchekavelo.tw1.ru/auth-service
    adminClientId : admin-cli
    username : admin
    password : admin
    realmName : social-network


ingress:
  name: user-service-ingress
  host: euchekavelo.tw1.ru