namespace: &namespace feature

database:
  storagePath: /user-service/postgresql-storage-feature
  service:
    nodePort: 30120


backendUserService:
  image:
    version: latest-feature
  service:
    nodePort: 30121


s3:
  service:
    ui:
      nodePort: 30122
    server:
      nodePort: 30123
  ingress:
    host: user-service-minio-feature.local
  volume:
    storagePath: /user-service/minio-storage-feature


zipkin:
  service:
    nodePort: 30124


ingress:
  host: user-service-feature.local